### PR TITLE
Add support for opening sub-directories

### PR DESCRIPTION
**Pull request by martinRenou**

### CODE REVIEW

**Comment by martinRenou** [comment]
Opening as draft for now, I see some issues when coming back to the root, and in the sub-dirs paths

subdirs

**Comment by martinRenou** [comment]
Thinking more about it I am really not happy about this implementation, I will rework it.

**Comment by jtpio** [comment]
No problem, thanks @martinRenou for starting this!

**Comment by martinRenou** [comment]
It now works like a charm :)

subdirs

**Comment by martinRenou** [comment]
Actually the saving behavior that was introduced seem to fail now, I need to check what's happening

**Comment by martinRenou** [comment]
I deleted the branch by accident, reopened in https://github.com/jtpio/jupyterlab-filesystem-access/pull/11

**Pull request closed without merging**
